#!/usr/bin/env bash

# Activation or deactivation for audio record and webcam
function stream_control() {

    if [ "$1" == "enable" ]; then

	echo "Enabling audio record"
        sysctl kern.audio.record=1

	echo "Enabling webcam record"
	sysctl kern.video.record=1

        exit 0
    elif [ "$1" == "disable" ]; then

        echo "Disabling audio record"
        sysctl kern.audio.record=0

	echo "Disabling webcam record"
	sysctl kern.video.record=0

        exit 0
    else
        echo "Select a option. Valid options: enable or disable"
        exit 0
    fi
}

# Only root
function is_root_user() {
    if [ "$USER" != "root" ]; then
        echo "Permissions denied."
        echo "For only root/admin user"
        echo "Use sudo/doas for eleveted privilegies"
        exit
    else
	# Init function
	stream_control $1
    fi
}

# Function init
is_root_user $1
