#!/usr/local/bin/bash

# Cambiar las opciones para adjustarlas a tus necesidades

# Activamos o desactivamos VPNs adicionales en el sistema
function vpn_control() {

    if [ "$1" == "work" ]; then

	echo "Activando VPN Work..."

	# Activamos la ruta por defecto de la red
	echo "Cambiando ruta...192.168.10.1"
	route change default 192.168.10.1

	sleep 2

	# Firewall VPN
	echo "Firewall para tun0..."
	pfctl -F all
	pfctl -f /etc/pf.conf-tun0

	sleep 2

	# Activamos el VPN 01
	echo "Activando OpenVPN Work..."
	/usr/local/sbin/openvpn --daemon --config /etc/openvpn/work.ovpn &
        sleep 5

	echo "VPN Work activado."

        exit 0

    elif [ "$1" == "personal" ]; then

	echo "Activando Wireguard..."

	# Matando OpenVPN existente
	kill_vpn

	# Firewall VPN
	echo "Firewall para Wireguard..."
	pfctl -F all
	pfctl -f /etc/pf.conf

	# Reiniciando conexión Wireguard
	echo "Iniciando Wireguard..."
	route change default 10.0.0.1

	sleep 2

	echo "Wireguard activado."

        exit 0

    elif [ "$1" == "novpn" ]; then

	echo "Desactivando VPN..."

	# Detenemos OpenVPN
        kill_vpn
	
	# Reiniciamos las rutas por defecto
	echo "Cambiando ruta a 192.168.10.1..."
	route change default 192.168.10.1

	# Firewall simple
	echo "Cargando firewall para NoVPN..."
	pfctl -F all
	pfctl -f /etc/pf.conf-clean

	sleep 2

	echo "VPN Desactivado. Conexión directa."

        exit 0

    else
        echo "Indique alguna opción. Opciones válidas: enable o disable"
        exit 0
    fi
}

# Kill VPN
function kill_vpn() {
	echo "Matando proceso OpenVPN existente..."
	pkill openvpn
	sleep 5
}

# Comprobando permisos
# Primeros verificamos que el usuario tenga permisos de root
function is_root_user() {
    if [ "$USER" != "root" ]; then
        echo "Permiso denegado."
        echo "Este programa solo puede ser ejecutado por el usuario root"
        echo "Use sudo/doas para poder garantizar permisos administrativos"
        exit
    else
	# Iniciamos programa
	vpn_control $1
    fi
}

# Llamada a la función de inicialización
is_root_user $1
