#!/bin/ksh

# Configuración
LAN_GW="192.168.10.1"
VPN_GW="10.70.46.51"

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: Debes ser root (usa doas)."
    exit 1
fi

case "$1" in
    on)
	route -q delete default
        route -q add default -iface $VPN_GW
        echo "VPN Activada: $VPN_GW"
        ;;
    off)
	route -q delete default
        route -q add default $LAN_GW
        echo "VPN Desactivada (LAN): $LAN_GW"
        ;;
    status)
        # Extraemos solo la IP del gateway por defecto
        CURRENT_GW=$(netstat -rnf inet | awk '$1 == "default" {print $2}')
        
        if [ "$CURRENT_GW" = "$VPN_GW" ]; then
            echo "$CURRENT_GW (VPN)"
        elif [ "$CURRENT_GW" = "$LAN_GW" ]; then
            echo "$CURRENT_GW (NO VPN)"
        else
            echo "$CURRENT_GW (Desconocido/Otro)"
        fi
        ;;
    *)
        echo "Uso: $0 {on|off|status}"
        exit 1
        ;;
esac
